# Site settings
author: Katleiah Ramos
title: Katleiah Codes
header-img: img/home-bg.png
email: katleiahramos@gmail.com
copyright_name: Katleiah Ramos
description: > # this means to ignore newlines until "baseurl:"
  My Journey as I Make My Way Into the Tech World 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: katkodes
github_username:  katleiahramos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-minimal